# List allowed iniswaps here.
# Each element contains a list of characters that can be swapped with each
# other.

-
  - Apollo
  - Apollo Leg
  - ApolloDD
  - ProsecutorJustice
-
  - Athena Maid W
  - AthenaCykesSOJ
-
  - Butz
  - ButzEdgeworth
